#!/usr/bin/env python
import rospy
from geometry_msgs.msg import Twist



def left_right():
	twist = Twist()
	st1=raw_input("Enter the string")
	if st1=="left":
		twist.linear.x=5
	 while not rospy.is_shutdown():
        rospy.logwarn("Running the node, time {}".format(rospy.get_time()))
        rate.sleep()
    pass

if __name__ == '__main__':
   left_right()
